### ISSUE TITLE
Problems building duc-1.2 on OS X 10.10.3

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#88]
duc-1.2 fails to build on OS X 10.10.3 out-of-the box with XQuartz and macports installed. It fails to find X11 and when X11 is disabled it fails to find GLOB_TILDE_CHECK.

MBP:duc-1.2> ./configure
...
checking for tputs in -lncursesw... no
checking for tputs in -lncurses... yes
checking for XOpenDisplay in -lX11... no
configure: error: 
The X11 library was not found, which is needed for gui support. Either install
the X11 development libraries, or compile without gui support (--disable-gui)

MBP:duc-1.2> ./configure --disable-gui
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
...
 configuration summary:

   - Package version: duc 1.2
   - Prefix: /usr/local
   - Database backend: tokyocabinet
   - GUI (X11) support: no
   - UI (ncurses) support: yes
   - Graph drawing support: yes

MBP:duc-1.2> make
...
	gcc -DHAVE_CONFIG_H -I.    -I/opt/local/include/cairo -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include  -D_REENTRANT -I/opt/local/include/pango-1.0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include  -D_REENTRANT -I/opt/local/include/pango-1.0 -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/pango-1.0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include   -Isrc/libduc -Isrc/libduc-graph -g -O2 -MT src/libduc/duc.o -MD -MP -MF $depbase.Tpo -c -o src/libduc/duc.o src/libduc/duc.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/libduc/duc.c:114:12: error: use of undeclared identifier 'GLOB_TILDE_CHECK'
        glob(tmp, GLOB_TILDE_CHECK, NULL, db_list);
                  ^
1 error generated.
make[1]: *** [src/libduc/duc.o] Error 1
make: *** [all] Error 2

**Comment by zevv** [comment]
* On 2015-05-11 19:40:19 +0200, stuartthebruce wrote:
 
> duc-1.2 fails to build on OS X 10.10.3 out-of-the box with XQuartz and
> macports installed. 

Well, you're the first I know of to try to build Duc on macos X, so I'm
glad to get this fixed and add another OS to the tested-and-supported
list.

> It fails to find X11 

Could you send your config.log file, it might give me some ideas about
why X is not found.

> and when X11 is disabled it fails to find GLOB_TILDE_CHECK.

Hmmm, I admit the code using glob() is actually dead in the current
version. I just removed this code for now, since it is part of some
functionality that will need a lot of refactoring anyway, and we still
have the history in git.

Could you please clone the git master and try again? If you're not
comfortable with building from git I can make you a private .tgz as
well, let me know.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
> On May 11, 2015, at 11:09 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-05-11 19:40:19 +0200, stuartthebruce wrote:
> 
> > duc-1.2 fails to build on OS X 10.10.3 out-of-the box with XQuartz and
> > macports installed. 
> 
> Well, you're the first I know of to try to build Duc on macos X, so I'm
> glad to get this fixed and add another OS to the tested-and-supported
> list.
> 
> > It fails to find X11 
> 
> Could you send your config.log file, it might give me some ideas about
> why X is not found.

What is missing here is a check for /opt/X11/lib, which I believe is the default location that XQuartz installs X11. Note, X11 is not bundled with OS X by default. Here is the configure test program failing,

MBP:duc> cat test.c
#ifdef __cplusplus
extern "C"
#endif
char XOpenDisplay ();
int
main ()
{
return XOpenDisplay ();
  ;
  return 0;
}

MBP:duc> gcc test.c -lncurses -lm -lX11
ld: library not found for -lX11
clang: error: linker command failed with exit code 1 (use -v to see invocation)

and here it is working,

MBP:duc> gcc test.c -lncurses -lm -lX11 -L/opt/X11/lib
MBP:duc> echo $?
0

> 
> > and when X11 is disabled it fails to find GLOB_TILDE_CHECK.
> 
> Hmmm, I admit the code using glob() is actually dead in the current
> version. I just removed this code for now, since it is part of some
> functionality that will need a lot of refactoring anyway, and we still
> have the history in git.
> 
> Could you please clone the git master and try again? If you're not
> comfortable with building from git I can make you a private .tgz as
> well, let me know.

git master builds with —disable-gui and a few simple tests work. However, the graph command generates the following deprecation warning,

MBP:duc> ./duc graph /opt
May 11 14:03:22 MBP duc[75853] <Error>: The function ‘CGFontGetGlyphPath’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.
May 11 14:03:22 MBP duc[75853] <Error>: The function ‘CGFontGetGlyphPaths’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
* On 2015-05-11 23:05:44 +0200, stuartthebruce wrote:
 
> > Could you send your config.log file, it might give me some ideas
> > about why X is not found.
> 
> What is missing here is a check for /opt/X11/lib, which I believe is
> the default location that XQuartz installs X11. 

Ok, that's interesting. Not sure how to tell autoconf to look in /opt as
well, have you tried fiddling with CFLAGS/LDFLAGS? We're probably not
the first to run into this problem, I'll search a bit for a proper
solution.

> MBP:duc> gcc test.c -lncurses -lm -lX11 -L/opt/X11/lib 

Ok, you have a workaround, that's good.

> MBP:duc> ./duc graph /opt May 11 14:03:22 MBP duc[75853] <Error>: The
> function ‘CGFontGetGlyphPath’ is obsolete and will be removed in an
> upcoming update. Unfortunately, this application, or a library it
> uses, is using this obsolete function, and is thereby contributing to
> an overall degradation of system performance.  

Funny, that's probably caused by the pango library for MacOS X, because
Duc does not call any of these functions.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
> On May 11, 2015, at 2:48 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-05-11 23:05:44 +0200, stuartthebruce wrote:
> 
> > > Could you send your config.log file, it might give me some ideas
> > > about why X is not found.
> > 
> > What is missing here is a check for /opt/X11/lib, which I believe is
> > the default location that XQuartz installs X11. 
> 
> Ok, that's interesting. Not sure how to tell autoconf to look in /opt as
> well, have you tried fiddling with CFLAGS/LDFLAGS? We're probably not
> the first to run into this problem, I'll search a bit for a proper
> solution.

Setting LDFLAGS does get it to compile and link, but there is probably a
standard way to capture this in the configure script,

env LDFLAGS=-L/opt/X11/lib ./configure 

> 
> > MBP:duc> gcc test.c -lncurses -lm -lX11 -L/opt/X11/lib 
> 
> Ok, you have a workaround, that’s good.

While the curses ui display looks correct the X11 gui display has problems
displaying strings and numbers. I am not sure if the following attachments
will make it through to you but here are 2 examples,






> 
> > MBP:duc> ./duc graph /opt May 11 14:03:22 MBP duc[75853] <Error>: The
> > function ‘CGFontGetGlyphPath’ is obsolete and will be removed in an
> > upcoming update. Unfortunately, this application, or a library it
> > uses, is using this obsolete function, and is thereby contributing to
> > an overall degradation of system performance. 
> 
> Funny, that's probably caused by the pango library for MacOS X, because
> Duc does not call any of these functions.

FWIW, I am linking against pango 1.36.8 from MacPorts.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
* On 2015-05-12 01:31:28 +0200, stuartthebruce wrote:
 
> Setting LDFLAGS does get it to compile and link, but there is probably a
> standard way to capture this in the configure script,
> 
> env LDFLAGS=-L/opt/X11/lib ./configure 

I'm not sure how to tell autoconf to search in /opt/X11 as well. I'm no
auttools expert by far, but all other references I find seem to use the
same method as the above: setting the LDFLAGS variable when running
./configure. I think for now it will do if I add this to the build
instructions.

> While the curses ui display looks correct the X11 gui display has problems
> displaying strings and numbers. I am not sure if the following attachments
> will make it through to you but here are 2 examples,

Unfortunately there's no attachements. You should be able to upload
images with messages in the github issue.

> FWIW, I am linking against pango 1.36.8 from MacPorts.

Seems to be a macports issue: https://trac.macports.org/ticket/45599

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
Here are two example X11 gui displays under Yosemite that have less than ideal labels.

![pastedgraphic-4](https://cloud.githubusercontent.com/assets/12385914/7598399/c6f2ade2-f8ae-11e4-807a-6e6226492d4d.png)

![pastedgraphic-5](https://cloud.githubusercontent.com/assets/12385914/7598402/cd04b590-f8ae-11e4-82f2-28890d6fcc01.png)

**Comment by stuartthebruce** [comment]
> On May 12, 2015, at 6:08 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> > While the curses ui display looks correct the X11 gui display has problems
> > displaying strings and numbers. I am not sure if the following attachments
> > will make it through to you but here are 2 examples,
> 
> Unfortunately there's no attachements. You should be able to upload
> images with messages in the github issue.

I have uploaded two images.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
* On 2015-05-12 23:00:47 +0200, stuartthebruce wrote:
 
> I have uploaded two images.

Something is indeed completely broken here. Given the warnings caused by
cairo, I suspect the problem is not in duc, but in the cairo and/or
pango library ports for macos. I'm unfortunately not able to reproduce
or investigate as I do not have access to a MacOS machine myself.

If you have the time and courage you could ask for support at the people
from MacPorts; there seem to be known issues on which people have been
working the last few days, see the link I posted earlier.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
> On May 12, 2015, at 2:12 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-05-12 23:00:47 +0200, stuartthebruce wrote:
> 
> > I have uploaded two images.
> 
> Something is indeed completely broken here. Given the warnings caused by
> cairo, I suspect the problem is not in duc, but in the cairo and/or
> pango library ports for macos. I'm unfortunately not able to reproduce
> or investigate as I do not have access to a MacOS machine myself.
> 
> If you have the time and courage you could ask for support at the people
> from MacPorts; there seem to be known issues on which people have been
> working the last few days, see the link I posted earlier.

This is not a high priority for me so I will track the the macports updates
to pango/ciaro and try again later.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson
